
engine_git: https://github.com/Natay/biostar-central.git
engine_dir: "/home/www/biostar-central"

scripts_dir: "/home/www/biostar-central/themes/bioconductor/conf/scripts"
conf_dir : "/home/www/biostar-central/themes/bioconductor/conf"

bin_dir: "/export/bin"
src_dir: "/export/src"
ref_dir: "/export/refs"

django_settings_module: "themes.bioconductor.settings"

# Installs recipe dependencies.
install: False
restart: False
reset: False

conda_activate: "/home/www/miniconda3/envs/engine/bin/activate"
conda_env: "engine"

conda_url: https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
conda_dir: "~/miniconda3"

conda_environments:
  - { name: "{{conda_env}}", python_version: 3.6}
  - { name: test, python_version: 3.6}
  - { name: py2, python_version: 2}

conda_modify_path: yes

conda_rcfile: "~/.bashrc"

conda_add_condarc: yes
