# Generated by Django 3.0.4 on 2020-03-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_logger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.IntegerField(choices=[(0, 'Schueler'), (1, 'Lehrer'), (2, 'Admin')], default=0),
        ),
    ]
