# Generated by Django 3.0.4 on 2020-03-22 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_logger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='scholar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twitter',
        ),
    ]
